name: Email sender
on:
    workflow_call:
    workflow_dispatch:

jobs:
    email:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Send mail with attachment
              uses: dawidd6/action-send-mail@v16
              with:
                server_address: smtp.gmail.com
                server_port: 465
                secure: true
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                #subject: ${{ steps.python_entrypoint.outputs.email_title }}
                subject: "Hargreaves Lansdown Report"
                from: "Amine Upwork <lysergically8@gmail.com>"
                to: ${{ secrets.EMAIL_DEV }}
                #body: ${{ steps.status_body.outputs.email_body }}
                #attachments: spreadsheet/chelsea_financial.xlsx,spreadsheet/halifax.xlsx,spreadsheet/iweb.xlsx,spreadsheet/quilter.xlsx,spreadsheet/standard_life.xlsx,spreadsheet/willis_owen.xlsx,spreadsheet/financial_discount.xlsx
                #body: ${{ steps.email_prep.outputs.email_body }}
                body: "hl.xlsx report"

                attachments: spreadsheet/hl.xlsx